spring.application.name=SmartContractor

#server.port=${PORT:8080}
#
##DB configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update




#
#server.port=${PORT:8080}
#
##DB configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL:smartcontractor-postgresql-landt}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:db_smart_contractor_user}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jrm0efckUlteFmVsN7NHUnqxytoVRmhR}
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#


#
server.port=${PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



##Port configuration
#server.port=8080
##server.port=8080
#server.address=0.0.0.0
#
##DB configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=create
