spring.application.name=SmartContractor

#Port configuration
#server.port=5432
#server.port=8080
#server.address=0.0.0.0

server.port=${SPRING_DATASOURCE_PORT}

#DB configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


##Port configuration
#server.port=8081 //port on which your application will be running
#server.address=0.0.0.0 // to enable this app to phone

##DB configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres //here postgres is our DB name
#spring.datasource.username=postgres // username that you have given while installing postgres
#spring.datasource.password=admin // password that you have specified while installing postgres
#spring.jpa.show-sql=true // TO see all the SQL statements runned by hibernate
#spring.jpa.properties.hibernate.format_sql=true //Format the hibernate queries, statements
##spring.jpa.hibernate.ddl-auto=create-drop //This will create schema on running your application and will also drop all schemas once you stop your application
